FROM mcr.microsoft.com/vscode/devcontainers/javascript-node:16-bullseye

RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
    && apt-get -y install --no-install-recommends postgresql-client